#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V
bspc monitor VGA-1 -d VI VII VIII IX X 

feh --randomize --bg-scale $HOME/.config/wallpapers/* &

setxkbmap -option grp:alt_shift_toggle 'us,br'

sh $HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
nitrogen --restore &

bspc config border_width            2.5
bspc config window_gap              5

bspc config split_ratio             0.55
bspc config borderless_monocle      true
bspc config single_monocle          true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config normal_border_color     "#3f3a3c"
bspc config active_border_color     "#bd93f9"
bspc config focused_border_color    "#928373"
bspc config presel_feedback_color   "#448488"


xrandr --output VGA-1 --mode 1360x768 --pos 0x312 --rotate normal --output DVI-D-1 --off --output HDMI-1 --primary --mode 1920x1080 --pos 1360x0 --rotate normal
